title: 동현의 나불나불
description: "배우고 활용한 것들을 기록하는 블로그 입니다."
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/goyang.jpg"

# Social Links
email: aaabbb4202@naver.com
github_username: DonghyeonHDH
# twitter_username: twitter
instagram_username: ddonghyeon_42
# linkedin_username: linkedin
facebook_username: 황동현

# External API
# giscus_repo: "byanko55/jekyll-theme-satellite"
giscus_repo: "DonghyeonHDH/DonghyeonHDH.github.io"
# giscus_repoId: "R_kgDOJ6fqWg"
giscus_repoId: "R_kgDOSDDZpQ"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOSDDZpc4C7rnz"
goatcounter_code: byanko77
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
